name: TesteTecnicoPlugin
version: '1.0-SNAPSHOT'
main: br.com.thiago.testeTecnicoPlugin.Main
api-version: '1.21'
commands:
  sethome:
    description: Define uma nova home.
  home:
    description: Teleporta para a home definida.
  setAttributesWindCharge:
    description: Altera os Atributos do WindCharge
    usage: /setAttributesWindCharge <dano> <velocidade>
